# Generated by Django 5.0.2 on 2024-03-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=64, unique=True)),
                ('liga', models.CharField(max_length=64)),
                ('miasto', models.CharField(blank=True, max_length=64)),
                ('rok_powstania', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('wartosc_zespolu', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('opis', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Zawodnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=64)),
                ('nazwisko', models.CharField(max_length=64)),
                ('klub', models.CharField(blank=True, max_length=64, unique=True)),
                ('data_urodzenia', models.DateField(blank=True, null=True)),
                ('wiek', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('opis', models.TextField(default='')),
            ],
        ),
    ]
