# Generated by Django 5.0.2 on 2024-03-30 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluby', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sezon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinia', models.TextField(blank=True, default='')),
                ('start', models.DateField(blank=True, null=True)),
                ('koniec', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='klub',
            name='liga',
        ),
        migrations.RemoveField(
            model_name='klub',
            name='wartosc_zespolu',
        ),
        migrations.RemoveField(
            model_name='zawodnik',
            name='data_urodzenia',
        ),
        migrations.RemoveField(
            model_name='zawodnik',
            name='klub',
        ),
        migrations.RemoveField(
            model_name='zawodnik',
            name='opis',
        ),
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liga', models.PositiveSmallIntegerField(blank=True, choices=[(4, 'Ekstraklasa'), (3, 'La Liga'), (0, 'Bundesliga'), (1, 'Premier League'), (2, 'Serie A')], null=True)),
                ('wartosc_zespolu', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('trener', models.CharField(blank=True, max_length=50, null=True)),
                ('klub', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kluby.klub')),
            ],
        ),
    ]
