# Generated by Django 5.0.2 on 2024-03-30 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluby', '0002_sezon_remove_klub_liga_remove_klub_wartosc_zespolu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sezon',
            name='klub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kluby.klub'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='liga',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Bundesliga'), (4, 'Ekstraklasa'), (3, 'La Liga'), (2, 'Serie A'), (1, 'Premier League')], null=True),
        ),
    ]
