# Generated by Django 5.0.2 on 2024-03-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluby', '0003_sezon_klub_alter_extrainfo_liga'),
    ]

    operations = [
        migrations.AddField(
            model_name='zawodnik',
            name='kluby',
            field=models.ManyToManyField(to='kluby.klub'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='liga',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Premier League'), (4, 'Ekstraklasa'), (3, 'La Liga'), (0, 'Bundesliga'), (2, 'Serie A')], null=True),
        ),
    ]
