# Generated by Django 5.0.2 on 2024-03-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluby', '0004_zawodnik_kluby_alter_extrainfo_liga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='liga',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, 'Ekstraklasa'), (0, 'Bundesliga'), (2, 'Serie A'), (1, 'Premier League'), (3, 'La Liga')], null=True),
        ),
    ]
